emotion_name_for_cm = [
    "Happiness",
    "Sadness",
    "Neutral",
    "Anger",
    "Surprise",
    "Disgust",
    "Fear",
    "Contempt",
    "Anxiety",
    "Helplessness",
    "Disappointment",
]

class_name = [
    "happiness.",
    "sadness.",
    "neutral.",
    "anger.",
    "surprise.",
    "disgust.",
    "fear.",
    "contempt.",
    "anxiety.",
    "helplessness.",
    "disappointment.",
]
an_expression_of_name = [
    "an expression of happiness.",
    "an expression of sadness.",
    "an expression of neutral.",
    "an expression of anger.",
    "an expression of surprise.",
    "an expression of disgust.",
    "an expression of fear.",
    "an expression of contempt.",
    "an expression of anxiety.",
    "an expression of helplessness.",
    "an expression of disappointment.",
]
a_photo_of_a_face_with_an_expression_of_name = [
    "a photo of a face with an expression of happiness.",
    "a photo of a face with an expression of sadness.",
    "a photo of a face with an expression of neutral.",
    "a photo of a face with an expression of anger.",
    "a photo of a face with an expression of surprise.",
    "a photo of a face with an expression of disgust.",
    "a photo of a face with an expression of fear.",
    "a photo of a face with an expression of contempt.",
    "a photo of a face with an expression of anxiety.",
    "a photo of a face with an expression of helplessness.",
    "a photo of a face with an expression of disappointment.",
]

expression_ensemble_five = [
    # "Happiness":
    "an expression of happiness.",
    "a photo of a face with an expression of happiness.",
    "a photo radiating happiness in a person.",
    "a photo showing someone immersed in happiness.",
    "a photo capturing happiness within an individual.",
    # "Sadness": 
    "an expression of sadness.",
    "a cropped photo emphasizing a face expressing sadness.",
    "a photo exuding sadness in a person.",
    "a photo showing someone immersed in sadness.",
    "a photo capturing sadness within an individual.",
    # "Neutral":
    "an expression of neutral.",
    "a photo of a face with an expression of neutral.",
    "a photo radiating neutral in a person.",
    "a photo showing someone immersed in neutral.",
    "a photo capturing neutral within an individual.",
    # "Anger":
    "an expression of anger.",
    "a photo of a face with an expression of anger.",
    "a photo radiating anger in a person.",
    "a photo showing someone immersed in anger.",
    "a photo capturing anger within an individual.",
    # "Surprise":
    "an expression of surprise.",
    "a photo of a face with an expression of surprise.",
    "a photo radiating surprise in a person.",
    "a photo showing someone immersed in surprise.",
    "a photo capturing surprise within an individual.",
    # "Disgust":
    "an expression of disgust.",
    "a photo of a face with an expression of disgust.",
    "a photo radiating disgust in a person.",
    "a photo showing someone immersed in disgust.",
    "a photo capturing disgust within an individual.",
    # "Fear":
    "an expression of fear.",
    "a photo of a face with an expression of fear.",
    "a photo radiating fear in a person.",
    "a photo showing someone immersed in fear.",
    "a photo capturing fear within an individual.",
    # "Contempt":
    "an expression of contempt.",
    "a photo of a face with an expression of contempt.",
    "a photo radiating contempt in a person.",
    "a photo showing someone immersed in contempt.",
    "a photo capturing contempt within an individual.",
    # "Anxiety":
    "an expression of anxiety.",
    "a photo of a face with an expression of anxiety.",
    "a photo radiating anxiety in a person.",
    "a photo showing someone immersed in anxiety.",
    "a photo capturing anxiety within an individual.",
    # "Helplessness":
    "an expression of helplessness.",
    "a photo of a face with an expression of helplessness.",
    "a photo radiating helplessness in a person.",
    "a photo showing someone immersed in helplessness.",
    "a photo capturing helplessness within an individual.",
    # "Disappointment":
    "an expression of disappointment.",
    "a photo of a face with an expression of disappointment.",
    "a photo radiating disappointment in a person.",
    "a photo showing someone immersed in disappointment.",
    "a photo capturing disappointment within an individual.",
]
expression_ensemble_ten = [
    # "Happiness":
    "an expression of happiness.",
    "a photo of a face with an expression of happiness.",
    "a photo radiating happiness in a person.",
    "a photo showing someone immersed in happiness.",
    "a photo capturing happiness within an individual.",
    "a photo of a face exuding happiness.",
    "a photo of a person embodying happiness.",
    "a good photo capturing someone's happiness.",
    "a cropped photo emphasizing a face expressing happiness.",
    "a clean photo showcasing a person's happiness.",
    # "Sadness": 
    "an expression of sadness.",
    "a cropped photo emphasizing a face expressing sadness.",
    "a photo exuding sadness in a person.",
    "a photo showing someone immersed in sadness.",
    "a photo capturing sadness within an individual.",
    "a photo of a face displaying sadness.",
    "a photo of a person embodying sadness.",
    "a good photo capturing someone's sadness.",
    "a photo of a face with an expression of sadness.",
    "a clean photo showcasing a person's sadness.",
    # "Neutral":
    "an expression of neutral.",
    "a photo of a face with an expression of neutral.",
    "a photo radiating neutral in a person.",
    "a photo showing someone immersed in neutral.",
    "a photo capturing neutral within an individual.",
    "a photo of a face displaying neutral.",
    "a photo of a person embodying neutral.",
    "a good photo capturing someone's neutral state.",
    "a cropped photo emphasizing a face expressing neutral.",
    "a clean photo showcasing a person's neutral expression.",
    # "Anger":
    "an expression of anger.",
    "a photo of a face with an expression of anger.",
    "a photo radiating anger in a person.",
    "a photo showing someone immersed in anger.",
    "a photo capturing anger within an individual.",
    "a photo of a face displaying anger.",
    "a photo of a person embodying anger.",
    "a good photo capturing someone's anger.",
    "a cropped photo emphasizing a face expressing anger.",
    "a clean photo showcasing a person's angry expression.",
    # "Surprise":
    "an expression of surprise.",
    "a photo of a face with an expression of surprise.",
    "a photo radiating surprise in a person.",
    "a photo showing someone immersed in surprise.",
    "a photo capturing surprise within an individual.",
    "a photo of a face displaying surprise.",
    "a photo of a person embodying surprise.",
    "a good photo capturing someone's surprise.",
    "a cropped photo emphasizing a face expressing surprise.",
    "a clean photo showcasing a person's surprised expression.",
    # "Disgust":
    "an expression of disgust.",
    "a photo of a face with an expression of disgust.",
    "a photo radiating disgust in a person.",
    "a photo showing someone immersed in disgust.",
    "a photo capturing disgust within an individual.",
    "a photo of a face displaying disgust.",
    "a photo of a person embodying disgust.",
    "a good photo capturing someone's disgust.",
    "a cropped photo emphasizing a face expressing disgust.",
    "a clean photo showcasing a person's disgusted expression.",
    # "Fear":
    "an expression of fear.",
    "a photo of a face with an expression of fear.",
    "a photo radiating fear in a person.",
    "a photo showing someone immersed in fear.",
    "a photo capturing fear within an individual.",
    "a photo of a face displaying fear.",
    "a photo of a person embodying fear.",
    "a good photo capturing someone's fear.",
    "a cropped photo emphasizing a face expressing fear.",
    "a clean photo showcasing a person's fearful expression.",
    # "Contempt":
    "an expression of contempt.",
    "a photo of a face with an expression of contempt.",
    "a photo radiating contempt in a person.",
    "a photo showing someone immersed in contempt.",
    "a photo capturing contempt within an individual.",
    "a photo of a face displaying contempt.",
    "a photo of a person embodying contempt.",
    "a good photo capturing someone's contempt.",
    "a cropped photo emphasizing a face expressing contempt.",
    "a clean photo showcasing a person's contemptuous expression.",
    # "Anxiety":
    "an expression of anxiety.",
    "a photo of a face with an expression of anxiety.",
    "a photo radiating anxiety in a person.",
    "a photo showing someone immersed in anxiety.",
    "a photo capturing anxiety within an individual.",
    "a photo of a face displaying anxiety.",
    "a photo of a person embodying anxiety.",
    "a good photo capturing someone's anxiety.",
    "a cropped photo emphasizing a face expressing anxiety.",
    "a clean photo showcasing a person's anxious expression.",
    # "Helplessness":
    "an expression of helplessness.",
    "a photo of a face with an expression of helplessness.",
    "a photo radiating helplessness in a person.",
    "a photo showing someone immersed in helplessness.",
    "a photo capturing helplessness within an individual.",
    "a photo of a face displaying helplessness.",
    "a photo of a person embodying helplessness.",
    "a good photo capturing someone's helplessness.",
    "a cropped photo emphasizing a face expressing helplessness.",
    "a clean photo showcasing a person's helpless expression.",
    # "Disappointment":
    "an expression of disappointment.",
    "a photo of a face with an expression of disappointment.",
    "a photo radiating disappointment in a person.",
    "a photo showing someone immersed in disappointment.",
    "a photo capturing disappointment within an individual.",
    "a photo of a face displaying disappointment.",
    "a photo of a person embodying disappointment.",
    "a good photo capturing someone's disappointment.",
    "a cropped photo emphasizing a face expressing disappointment.",
    "a clean photo showcasing a person's disappointed expression.",
]


Emotion_name_dic = {
    "RAFDB": emotion_name_for_cm[0:7],
    "AffectNet7": emotion_name_for_cm[0:7],
    "AffectNet8": emotion_name_for_cm[0:8],
    "FERPlus": emotion_name_for_cm[0:8],
    "DFEW": emotion_name_for_cm[0:7],
    "FERV39k": emotion_name_for_cm[0:7],
    "MAFW": emotion_name_for_cm[0:11],
    "AFEW": emotion_name_for_cm[0:7]
}

FER_prompt_type_list = [
    'Class Name',
    'An Expression of Name',
    'A Photo of A Face with An Expression of Name',
    'Expression Ensemble Five',
    'Expression Ensemble Ten',
]

FER_prompt_list = [
    {"RAFDB": class_name[0:7],
    "AffectNet7": class_name[0:7],
    "AffectNet8": class_name[0:8],
    "FERPlus": class_name[0:8],
    "DFEW": class_name[0:7],
    "FERV39k": class_name[0:7],
    "MAFW": class_name[0:11],
    "AFEW": class_name[0:7]},

    {"RAFDB": an_expression_of_name[0:7],
    "AffectNet7": an_expression_of_name[0:7],
    "AffectNet8": an_expression_of_name[0:8],
    "FERPlus": an_expression_of_name[0:8],
    "DFEW": an_expression_of_name[0:7],
    "FERV39k": an_expression_of_name[0:7],
    "MAFW": an_expression_of_name[0:11],
    "AFEW": an_expression_of_name[0:7]},

    {"RAFDB": a_photo_of_a_face_with_an_expression_of_name[0:7],
    "AffectNet7": a_photo_of_a_face_with_an_expression_of_name[0:7],
    "AffectNet8": a_photo_of_a_face_with_an_expression_of_name[0:8],
    "FERPlus": a_photo_of_a_face_with_an_expression_of_name[0:8],
    "DFEW": a_photo_of_a_face_with_an_expression_of_name[0:7],
    "FERV39k": a_photo_of_a_face_with_an_expression_of_name[0:7],
    "MAFW": a_photo_of_a_face_with_an_expression_of_name[0:11],
    "AFEW": a_photo_of_a_face_with_an_expression_of_name[0:7]},

    {"RAFDB": expression_ensemble_five[0:35],
    "AffectNet7": expression_ensemble_five[0:35],
    "AffectNet8": expression_ensemble_five[0:40],
    "FERPlus": expression_ensemble_five[0:40],
    "DFEW": expression_ensemble_five[0:35],
    "FERV39k": expression_ensemble_five[0:35],
    "MAFW": expression_ensemble_five[0:55],
    "AFEW": expression_ensemble_five[0:35]},

    {"RAFDB": expression_ensemble_ten[0:70],
    "AffectNet7": expression_ensemble_ten[0:70],
    "AffectNet8": expression_ensemble_ten[0:80],
    "FERPlus": expression_ensemble_ten[0:80],
    "DFEW": expression_ensemble_ten[0:70],
    "FERV39k": expression_ensemble_ten[0:70],
    "MAFW": expression_ensemble_ten[0:110],
    "AFEW": expression_ensemble_ten[0:70]}
]